school management/website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, jsonify
from werkzeug.security import check_password_hash
from . import connectDB, enterDetails
from .models import User
from flask_login import logout_user, login_user, login_required, current_user

auth = Blueprint('auth', __name__)

@auth.route('/', methods = ['GET'])
def hero():
    return render_template('index.html')

#login route
@auth.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        data = request.get_json()
        username = data.get('username')
        password = data.get('password')
        print(f'{username} {password}')
        session['username'] = username

        with connectDB() as session_db:

            user = session_db.query(User).filter_by(username=username).first()

            if user:
                if check_password_hash(user.password, password):
                    flash('Conectat cu succes', category='success')
                    #add details in DB
                    if not enterDetails(user.id, 'connected to server'):
                        print('s-a produs o eroare, reincercati!', category='alert')
                    login_user(user, remember=True)
                    #redirect to reset page
                    if user.count == 0:
                        return redirect(url_for('views.reset_pass'))
                    role = user.rol
                    cal = user.calificare
                    return jsonify({'userRole': role, 'userCalif': cal}), 200
                else:
                    return jsonify({'message': 'wrong'}), 200
            else:
                return jsonify({'message': 'wrong'}), 200
    return render_template('login.html')


#logout route
@auth.route('/logout')
@login_required
def logout():
    #add details to DB
    if not enterDetails(current_user.id, 'disconnected from server'):
        flash('s-a produs o eroare, incercati din nou', category='alert')
    logout_user()
    return redirect(url_for('auth.login'))

school management/website/views.py
from flask import Blueprint, render_template, render_template_string, redirect, request, flash, url_for, jsonify
from flask import session as sesiune
from sqlalchemy import and_, desc, func
from flask_login import login_required, current_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from .models import Details, User, Events, Inventar, Schools
from . import db, connectDB, enterDetails, sendMail, format_datetime
from datetime import datetime
import random, os, shutil


views = Blueprint('views', __name__)


# check user type
def checkUserType(user_rol, user_type):
    if current_user.rol == 'admin':
        return True
    elif current_user.rol == str(user_rol) or current_user.calificare == str(user_type):
        return True
    else:
        flash('Conectati-va cu un alt cont pentru a accesa aceasta pagina.', category='alert')
        if not enterDetails(current_user.id, 'tried to access wrong page for his type'):
            print('Error at section user type check')
        logout_user()
        return False


def deleteFiles():
    path = os.path.join('website', 'static', 'directories')
    try:
        for item in os.listdir(path):
            item_path = os.path.join(path, item)
            if os.path.isfile(item_path) or os.path.islink(item_path):
                os.unlink(item_path)
            elif os.path.isdir(item_path):
                shutil.rmtree(item_path)
    except Exception as e:
        print(f'Error at deleteing files-background: {e}')


def returningEvents():
    with connectDB() as session:
        events = []
        events_entry = session.query(Events).filter(
            Events.user_id == current_user.id,
            Events.end >= datetime.now()
        ).order_by(Events.start.asc(), Events.end.asc()).all()
        if events_entry:
            for event in events_entry:
                event_start = format_datetime(event.start)
                event_end = format_datetime(event.end)
                if 'T' in event.start:
                    event_data = {
                        'id': event.id,
                        'title': event.title,
                        'start': event_start['month'],
                        'end': event_end['month'],
                        'start_time': event_start['time'],
                        'end_time': event_end['time'],
                        'weekDayStart': event_start['weekDay'],
                        'weekDayEnd': event_end['weekDay'] 
                    }
                else:
                    event_data = {
                        'id': event.id,
                        'title': event.title,
                        'start': event_start['month'],
                        'end': event_end['month'],
                        'weekDayStart': event_start['weekDay'],
                        'weekDayEnd': event_end['weekDay'] 
                    }
                events.append(event_data)
        return events


#admin template
@views.route('/admin', methods=['POST', 'GET'])
@login_required
def admin():
    try: 
        if checkUserType('admin', 'informatician'):
            deleteFiles()
            events = returningEvents()
            with connectDB() as session:
                # elevi
                elevi = session.query(User).filter(
                    User.school_id == current_user.school_id,
                    User.rol == 'elev'
                ).all()
                total_elevi = len(elevi) if elevi else 0

                liceu = session.query(User).filter(
                    User.school_id == current_user.school_id,
                    User.rol == 'elev',
                    (User.tipElev == 'liceu')
                ).all()
                total_liceu = len(liceu) if liceu else 0

                procentajLiceu = int(calcproc(total_liceu, total_elevi)) if elevi else 0

                prof = session.query(User).filter(
                    User.school_id == current_user.school_id,
                    User.rol == 'elev',
                    User.tipElev == 'profesionala'
                ).all()
                total_prof = len(prof) if prof else 0

                procentajProf = int(calcproc(total_prof, total_elevi)) if elevi else 0
                
                other = session.query(User).filter(
                    User.school_id == current_user.school_id,
                    User.rol == 'elev',
                    User.tipElev != 'liceu',
                    User.tipElev != 'profesionala'
                ).all()
                total_other = len(other) if other else 0

                procentajOther = int(calcproc(total_other, total_elevi)) if elevi else 0

                #staff
                staff = session.query(User).filter(
                    User.school_id == current_user.school_id,
                    User.rol != 'elev'
                ).all()
                total_staff = len(staff)
                
                didactic = session.query(User).filter(
                    User.school_id == current_user.school_id,
                    User.rol == 'profesor'
                ).all()
                total_didactic = len(didactic) if staff else 0

                procentajDidactic = int(calcproc(total_didactic, total_staff)) if staff else 0

                nedidactic = session.query(User).filter(
                    User.school_id == current_user.school_id,
                    (User.rol == 'director') |
                    (User.rol == 'tehnic')
                ).all()
                total_nedidactic = len(nedidactic) if staff else 0

                procentajNedidactic = int(calcproc(total_nedidactic, total_staff)) if staff else 0

                #inventar
                inventory = session.query(Inventar).filter_by(school_id = current_user.school_id).all()
                total_inventar = len(inventory) if inventory else 0

                invSum = sum(inv.cant for inv in inventory)
                
                invDidactic = []

                for user in didactic:
                    invDid = session.query(Inventar).filter(
                        Inventar.school_id == current_user.school_id,
                        Inventar.user_id == user.id
                    ).all()

                    if invDid:
                        invDidactic.append(invDid)

                procentajInvDid = int(calcproc(sum(len(inv_list) for inv_list in invDidactic) if didactic else 0, total_inventar))
                
                
                invNedidactic = []

                for user in nedidactic:
                    invNedid = session.query(Inventar).filter(
                        Inventar.school_id == current_user.school_id,
                        Inventar.user_id == user.id
                    ).all()

                    if invNedid:
                        invNedidactic.append(invNedid)
                    else:
                        continue
                procentajInvNedid = int(calcproc(sum(len(inv_list) for inv_list in invNedidactic) if nedidactic else 0, total_inventar))

                #files section
                school = session.query(Schools).filter_by(id = current_user.school_id).first()

                if school:
                    school_name = str(school.school_name).replace('"', '')
                
                folder_path = os.path.join('website', 'static', 'files', school_name)

                files = []

                if os.path.exists(folder_path):
                    file_names = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
                    files = [{'name': file_name.split('.')[0], 'type': file_name.split('.')[-1]} for file_name in file_names]
                
                # Count the occurrences of each file type
                file_type_counts = {}
                total_files = len(files)

                for file_info in files:
                    file_type = file_info['type']
                    file_type_counts[file_type] = file_type_counts.get(file_type, 0) + 1

                # Sort file types based on their frequency
                sorted_file_types = sorted(file_type_counts.items(), key=lambda x: x[1], reverse=True)

                # Calculate the percentage of each file type
                file_type_percentages = {file_type: round((count / total_files) * 100) for file_type, count in sorted_file_types}

                # Create a list to store first and second types along with percentages
                result = []

                # Separate the first two file types
                if len(sorted_file_types) >= 2:
                    first_type = {'name': str(sorted_file_types[0][0]).upper(), 'percentage': file_type_percentages.get(sorted_file_types[0][0], 0)}
                    second_type = {'name': str(sorted_file_types[1][0]).upper(), 'percentage': file_type_percentages.get(sorted_file_types[1][0], 0)}
                    other_percentage = sum(file_type_percentages.get(file_type, 0) for file_type, count in sorted_file_types[2:])
                else:
                    # Handle the case where there are less than two file types
                    first_type, second_type, other_percentage = None, None, 0

                # Append first and second types to the result list
                if first_type:
                    result.append(first_type)
                if second_type:
                    result.append(second_type)

                # Append "other" entry to the result list
                result.append({'name': 'other', 'percentage': other_percentage})

                #recently table results
                users=[]

school management/website/templates/chat.html
{% extends 'base.html' %}
{% block content %}
    <form method = 'POST' action="{{url_for('chat.chat')}}" class="chat-form">
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input class="form-control" type="text" placeholder="{{current_user.username}}" aria-label="Disabled input example" name="username" disabled>
        </div>
        <div class="mb-3">
            <label for="join" class="form-label">Join a room</label>
            <div class="join">
                <input type="text" class="form-control" id="exampleFormControlInput1" name="join" >
                <button type="submit" name="join-btn" class="btn btn-primary">Join</button>
            </div>
        </div>
        <button type="submit" name="create" class="btn btn-primary">Create a room</button>
    </form>
{% endblock %}

school management/website/templates/director.html
{% extends 'base.html' %}
{% block content %}

<div class="links">
  <a href="{{url_for('views.confirmEmail')}}">Resetare parola</a>
  <a href="{{url_for('views.reset_user')}}">Resetare username</a>
  <a href="{{url_for('chat.chat')}}">WebChat</a>
  <a href="{{url_for('qread.qrscanner')}}">Scanare QRCode</a>
  <a href="{{url_for('import.add_files')}}">Adaugare Fisier</a>
  <a href="{{url_for('import.add_inventar')}}">Adaugare Inventar</a>
  <a href="{{url_for('import.downloadQrDirectory')}}" download>Descarca Codurile QR</a>
  <a href="{{url_for('views.calendarGenerator')}}">Calendar</a>
  <a href="{{url_for('import.inventarTransfer')}}">Transfer Inventar</a>
  <a href="{{url_for('news.requests')}}">Actualizări</a>
</div>

<!-- Cloudflare Pages Analytics -->
<script defer src='https://static.cloudflareinsights.com/beacon.min.js'
  data-cf-beacon='{"token": "dc4641f860664c6e824b093274f50291"}'></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var calendarElem = document.getElementById('calendar-front');
    var calendar = new FullCalendar.Calendar(calendarElem, {
      timeZone: 'Europe/Romania',
      headerToolbar: {
        left: 'prev',
        center: 'title',
        right: 'next'
      },
      dateClick: function (info) {
        var clickedDate = info.date.toISOString();
        window.location.href = '/calendar?date=' + clickedDate + '&view=timeGridDay';
      },
      initialView: 'timeGridDay',
      selectable: true,
      navLinks: true,
      firstDay: 1,
      locale: 'ro',
      height: 400,
      aspectRatio: 3,
      events: [
        {% for event in events %}
        {
            id: '{{event.id}}',
            title: '{{event.title}}',
            start: '{{event.start}}',
            end: '{{event.end}}',
        },
        {% endfor %}
        ],
    });
    calendar.render();
  });
</script>
<div class="calendar-container">
  <div id="calendar-front" class="calendar-front"></div>
</div>
<script src='{{url_for("static", filename="fullcalendar/dist/index.global.js")}}'></script>
{% endblock %}

school management/website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
    <link rel="stylesheet" href="{{url_for('static', filename='hero.css')}}">
    <script src="{{url_for('static', filename='base.js')}}"></script>
</head>
<body>
    <div class="form">   
        <form method = 'POST' action="{{url_for('auth.login')}}">
            <div class="logo">SchoolSYS</div>
            <legend>Log In</legend>
            <div class="usernameArea">
                <input type="text" id="username" name="username" placeholder="Username *" value="{{ username }}" required autocomplete="username">
            </div>
            <div class="passowordArea">
                <input type="password" placeholder="Parolă *" id="password" name="password" required autocomplete="current-password">
            </div>
            <div class="mb-3 form-check">  
                <input type="checkbox" id="exampleCheck" onchange="showPassword()">
                <label for="exampleCheck">Check me out</label>
            </div>
            <div class="registerLink">
                Nu ai cont? <a href="{{url_for('auth.hero')}}">Crează-ți unul</a>
            </div>
            <button type="submit" id="loginBtn">Login</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function() {
            $("#loginBtn").on('click', function(event) {
                event.preventDefault();

                username = $("#username").val();
                password = $("#password").val();

                $.ajax({
                    url: '{{url_for("auth.login")}}',
                    method: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify({username: username, password: password}),
                    success: function(data){
                        if (data.message === 'wrong') {
                            Swal.fire({
                                icon: "error",
                                title: "User inexistent",
                                text: "Parola sau username greșit",
                                confirmButtonText: 'OK',
                            }).then(function() {
                                location.reload();
                            });
                        } else {
                            redirectHomePage(data.userRole, data.userCalif);
                        }
                    },
                    error: function(message){
                        console.error('Error', message)
                    }
                });
            });
        });
          function redirectHomePage(role, calif) {
      
            var homePageURL;
            switch (role) {
              case "admin":
                homePageURL = "{{url_for('views.admin')}}";
                break;
              case "director":
                homePageURL = "{{url_for('views.director')}}";
                break;
              case "profesor":
                homePageURL = '{{url_for("views.teacher")}}';
                break;
              case "elev":
                homePageURL = '{{url_for("views.student")}}';
                break;
              case "tehnic":
                if (calif == "informatician") {
                  homePageURL = '{{url_for("views.admin")}}';
                } else {
                  <!--TODO change to 'views.tehnic after create the route'-->
                  homePageURL = "/tehnic";
                }
                break;
              default:
                homePageURL = "/";
                break;
            }
            window.location.href = homePageURL;
          }
    </script>
</body>
</html>

school management/website/templates/qrscanner.html
{% extends 'base.html' %}
{% block title %}
    QR Scanner
{% endblock %}
{% block content %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js"></script>
    <script>
        var socket = io.connect('http://' + document.domain + ':' + location.port + '/qrscanner');

        // Handle the 'qr_detected' event
        socket.on('qr_detected', function(data) {
            // Redirect to the specified URL using url_for
            var redirectUrl = '{{ url_for("results.result") }}?query=' + encodeURIComponent(data.query);
            window.location.href = redirectUrl;
        });

        // Handle page unload or URL change
        window.addEventListener('beforeunload', function() {
            socket.emit('close_page', {message: 'Closing the page'});
        });

    </script>

    <!-- Display the live video feed -->
    <div class="video-tab">
        <img src="{{url_for('qread.videoStreaming')}}" width="640" height="480" alt="VideoStreaming">
    </div>
{% endblock %}

school management/website/templates/reset.html
{% extends 'base.html' %}
{% block title %}
    Reset Password
{% endblock %}
{% block content %}

<!-- Confirm Email-->
<div class="modal fade" id="confirmEmail" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="emailConfirm" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Resetare Parola</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="closeBtn-email"></button>
      </div>
      <div class="modal-body">
        <div class="form-floating mb-3">
          <input type="email" class="form-control" id="email" name="email" placeholder="Introduceti Email" autocomplete required>
          <label for="email">Introduceti Email</label>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="sendEmail" class="btn btn-primary">Trimite link</button>
      </div>
    </div>
  </div>
</div>


<!-- Verify OTP -->
<div class="modal fade" id="verifyOTP" tabindex="-1" role="dialog" aria-labelledby="otpModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="otpModalLabel">Introdu codul primit pe email</h5>
              <button type="button" id="close-otp" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="description">
                Daca email-ul este corect, vei fi primi un cod unic, valabil 5 minute(Verificati si SPAM). 
            </div>
              <div class="form-row">
                  <div class="form-group col-md-2">
                      <input type="text" class="form-control otp-input" maxlength="1" id="otp1" required>
                  </div>
                  <div class="form-group col-md-2">
                      <input type="text" class="form-control otp-input" maxlength="1" id="otp2" required>
                  </div>
                  <div class="form-group col-md-2">
                      <input type="text" class="form-control otp-input" maxlength="1" id="otp3" required>
                  </div>
                  <div class="form-group col-md-2">
                      <input type="text" class="form-control otp-input" maxlength="1" id="otp4" required>
                  </div>
                  <div class="form-group col-md-2">
                      <input type="text" class="form-control otp-input" maxlength="1" id="otp5" required>
                  </div>
                  <div class="form-group col-md-2">
                      <input type="text" class="form-control otp-input" maxlength="1" id="otp6" required>
                  </div>
              </div>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-primary" id="otpbtn">Verify OTP</button>
          </div>
      </div>
  </div>
</div>

<!-- Password Reset -->
<div class="modal fade" id="staticBackdrop-pass" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Resetare Parola</h1>
        {% if current_user.count%}
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="closeModalBtn"></button>
        {% endif%}
      </div>
      <div class="modal-body">
        <form method="POST" id="resetForm">
          <label for="inputPassword5" class="form-label">Parolă nouă</label>
          <input type="password" id="password_reset" name="password_reset" class="form-control" aria-describedby="passwordHelpBlock" autocomplete="New Password" required>
          <div id="passwordHelpBlock" class="form-text">
              Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
          </div>
          <div class="mb-3 form-check">  
              <input type="checkbox" class="form-check-input" id="exampleCheck_reset" onchange="showPassword_reset()">
              <label class="form-check-label" for="exampleCheck_reset">Check me out</label>
          </div>
          <label for="inputPassword5" class="form-label">Confirmă parola</label>
          <input type="password" id="password_confirm" name="password_confirm" class="form-control" aria-describedby="passwordHelpBlock" autocomplete="New Password" required>
          <div class="mb-3 form-check">  
              <input type="checkbox" class="form-check-input" id="exampleCheck_confirm" onchange="showPassword_confirm()">
              <label class="form-check-label" for="exampleCheck_confirm">Check me out</label>
          </div>
          {% if user %}
          <div class="form-check form-check-reverse">
            <input class="form-check-input" type="checkbox" value="1" name="reset_connect" id="reset_connect">
            <label class="form-check-label" for="reset_connect">
                Schimbare parola la conectare?
            </label>
          </div>
          {% endif %}
          <button type="submit" class="btn btn-primary">Schimbă parola</button>
      </form>
      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>


<!-- Username Reset -->
<div class="modal fade" id="staticBackdrop-user" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabelUser">Schimbare Username</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="closeModalBtn-user"></button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{{ url_for('views.reset_user') }}">
          <label for="inputPassword5" class="form-label">Username vechi</label>
          <input type="text" id="user_reset" name="user_reset" class="form-control" autocomplete="username" required>

          <label for="inputPassword5" class="form-label">Username Nou</label>
          <input type="text" id="username_confirm" name="username_confirm" class="form-control" autocomplete="new username" required>
              <button type="submit" class="btn btn-primary">Schimbă Username</button>
        </form>
      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>


  <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha384-..." crossorigin="anonymous"></script>

  <!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="..."></script>

<!-- Send Email confirmation -->
<script>
  $(document).ready(function() {
    $("#sendEmail").on("click", function() {
      var emailValue = $("#email").val();
      
      // Validate the email format using a regular expression
      var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(emailValue)) {
        alert("Invalid email format");
        return;
      }

      $.ajax({
        type: "POST",
        url: "{{url_for('views.confirmEmail')}}",
        data: {email: emailValue},
        success: function(response) {
          window.location.href = "{{url_for('views.verifyOTP')}}";
        },
        error: function(error){
          console.error("Error: ", error);
        }
      });
    });
  });
</script>

<!-- Verify OTP Code-->
<script>
  $(document).ready( function() {
    $('.otp-input').on('input', function() {
      var maxLength = parseInt($(this).attr('maxlength'), 10);

      var currentValue = $(this).val();

      if (currentValue && currentValue.length === maxLength) {
        var nextInput = $(this).closest('.form-group').next().find('.otp-input');

        if (nextInput.length) {
          nextInput.focus();
        }
      }
    });

    $('#otpbtn').on('click', function() {
      var otp = '';
      otp+= document.getElementById('otp1').value;
      otp+= document.getElementById('otp2').value;
      otp+= document.getElementById('otp3').value;
      otp+= document.getElementById('otp4').value;
      otp+= document.getElementById('otp5').value;
      otp+= document.getElementById('otp6').value;

      $.ajax({
        type: 'POST',
        url: "{{url_for('views.verifyOTP')}}",
        data: {otp: otp},
        success: function(response){
          window.location.href = "{{url_for('views.reset_pass')}}";
        },
        error: function(error) {
          alert('Codul nu este corect')
          console.error('Error: ', error);
        }
      });
    });
  });
</script>

{% if user %}
  <script>
    $(document).ready(function () {
      var Url = window.location.href;

      if (Urls.includes("reset_change")){
        $("resetForm").attr('action', "{{url_for('import.reset_password', user_id=user.id)}}")
      }
      else{
        $("resetForm").attr('action', "{{url_for('views.reset_pass')}}")
      }
    })
  </script>
{% endif %}


<!-- show different modal -->
<script>
  $(document).ready(function () {
      var currentUrl = window.location.href;
      if (currentUrl.includes("reset_pass") || (currentUrl.includes("reset_change"))) {
          $('#staticBackdrop-pass').modal('show');
      } else if (currentUrl.includes("reset_user")) {
          $('#staticBackdrop-user').modal('show');
      } else if (currentUrl.includes("confirm-email")){
          $('#confirmEmail').modal('show');
      } else if (currentUrl.includes("verifyOTP")){
          $('#verifyOTP').modal('show');
      }
  });
</script>

<script>
  function getUserRole() {
    return "{{ current_user.rol }}";
  }

  function getUserCalificare() {
    return "{{ current_user.calificare}}";
  }

  function redirectHomePage() {
    var user_role = getUserRole();
    var user_calif = getUserCalificare();

    var homePageURL;
    switch (user_role) {
      case "admin":
        homePageURL = "{{url_for('views.admin')}}";
        break;
      case "profesor":
        homePageURL = '{{url_for("views.teacher")}}';
        break;
      case "elev":
        homePageURL = '{{url_for("views.student")}}';
        break;
      case "tehnic":
        if (user_calif == "informatician") {
          homePageURL = '{{url_for("views.admin")}}';
        } else {
          <!--TODO change to 'views.tehnic after create the route'-->
          homePageURL = "/tehnic";
        }
        break;
      default:
        homePageURL = "/";
        break;
    }
    window.location.href = homePageURL;
  }
  var closeBtns = document.querySelectorAll('.btn-close');
  closeBtns.forEach(function (closeBtn) {
    closeBtn.addEventListener('click', function(event) {
      event.preventDefault();
      redirectHomePage();
    });
  });
</script>

{% endblock %}

school management/website/templates/teacher.html
{% extends 'base.html' %}